### ISSUE TITLE
add readme.md

### ISSUE THREAD

**Issue by emilkone** [Aaron-Hsieh-0129/blood_velocity_NS_equation#1]
Hello. Can you add Readme.md with explanations for this project? I will be very grateful

**Comment by Aaron-Hsieh-0129** [comment]
Hi, I have uploaded my report. Because it's a toy project and the code is a little messy (I just started coding at that time), if you have any questions please let me know.

**Comment by emilkone** [comment]
Thank you. It helps me understand the code better
